language: node_js
node_js:
- stable
env:
  global:
    secure: trxrhCLvA/Bxs+E1QV9J70E+qBqF3Ied6+yldCkQoLfTrAxONLqoM02p92dDclWZsDjJanMTiJ7dZNwhfszd3zL/Yg3M2c5D4RRgeZehGHKe2EEcgQKDd/urPf3AxicNQ99ZtH09DFjD7Irgs6aatgJSPHXKzgmkgGCIGlF1/qHXw2PzPSf0sX+JaAvtTQvE5BctmwIRcHgV0UVCO2KvNXc8s5PMKgbn2iaP+TW/J2uiyV7Dxu51ukkGOHHq4OnXmIn+sPyiUrwVXN4GeLFU0MSwPziu1YQldu3hQOfzSMPIVKgJFP+sd0Ux/CBZXYq6pQ/DtH4RRRokR4mH9jjAg0hxjr3hkeVYuEgWzGzM0JK4nHLyKHkCJ1/XLU+d1clfFmjkfwaFV05wkGB04wX8pO9m2w9P/MrS66xp68eESOwWhmkC5IuEDlKCTjfOBUGcZkyZEPumkLO03u87D8CEYhN/jyvF/ELaERtWQ0lvaWdD5f4hswlhITA68ViLA+EmFm4QqgtuHCJDLiwYUvG/l1sJC7wmHb1dNqDGw37nTB1APaewCB5SmGVKtBIwzpkSthNgnCRtVScbYMDnzx9EVx0uEO2DfrZReUSp+iPErcDJbptKbVGaqpVWVEKhjS18D7cXAc8imm6963ZNMP8ZK52jlqdIRM/z+3EMuiYel0A=
